# Change these first
owner: ultreiac # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository
user-agent: ultreiac
i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  liveStatus: Estado actual
  pastIncidents: Incidentes pasados
  averageResponseTime: "Tiempo de respuesta medio: $TIMEms"
  overallUptime: "Tiempo de funcionamiento: $UPTIME"
  footer: ---
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
sites:
  - name: Ultreia Web
    url: https://ultreia.es
    __dangerous__body_down_if_text_missing: 'personal'
  - name: Empleo Ultreia
    url: https://empleo.ultreia.es/
    __dangerous__body_down_if_text_missing: 'requisitos'
  - name: Froiz - Web Corporativa
    url: https://froiz.es
    __dangerous__body_down_if_text_missing: 'Promociones'
  - name: Froiz - Tienda
    url: https://www.froiz.com/shop/
    __dangerous__body_down_if_text_missing: 'Promociones'
  - name: Ocionorte
    url: https://salapelicano.ocionorte.com/
    __dangerous__body_down_if_text_missing: 'Eventos'
  - name: Webmail Ticaas
    url: https://webmail.ticaas.net
    __dangerous__body_down_if_text_missing: 'Iniciar'
  - name: La Ondarresa
    url: https://www.laondarresa.eus
    __dangerous__body_down_if_text_missing: 'mar'
  - name: MiHogarDigital albarán
    url: https://www.mihogardigital.es
    __dangerous__body_down_if_text_missing: 'mihogardigital'
  - name: El Mar
    url: https://elmar.es
    __dangerous__body_down_if_text_missing: '1956'
  - name: De vinos con Alicia
    url: https://www.devinosconalicia.com
  - name: Ticaas IMAP (143)
    check: "tcp-ping"
    url: mail.ticaas.net
    port: 143
  - name: Ticaas POP (110)
    check: "tcp-ping"
    url: mail.ticaas.net
    port: 110
  - name: Ticaas SMTP (25)
    check: "tcp-ping"
    url: smtp.ticaas.net
    port: 25
  - name: CF Ticaas DNS 1
    check: "tcp-ping"
    url: kianchau.ns.cloudflare.com
    port: 53
  - name: CF Ticaas DNS 2
    check: "tcp-ping"
    url: naomi.ns.cloudflare.com
    port: 53
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: 
  baseUrl: /monitor
  logoUrl: https://ultreia.es/wp-content/uploads/logo_ultreia_byn-300x255.png
  name: Uptime monitor
  introTitle: "Ultreia Comunicaciones S.L"
  introMessage: "Estado de los servidores:"
  navbar:
    - title: Estado
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
