# Change these first
owner: ultreiac # Your GitHub organization or username, where this repository lives
repo: monitor # The name of this repository

sites:
  - name: Ultreia
    url: https://ultreia.es
  - name: Webmail Ticaas
    url: https://webmail.ticaas.net
  - name: Ticaas DNS 1
    check: "tcp-ping"
    url: kianchau.ns.cloudflare.com
    port: 53
  - name: Ticaas DNS 2
    check: "tcp-ping"
    url: naomi.ns.cloudflare.com
    port: 53
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: 
  baseUrl: /monitor
  logoUrl: https://ultreia.es/wp-content/uploads/logo_ultreia_byn-300x255.png
  name: Upptime
  introTitle: "Ultreia Comunicaciones S.L"
  introMessage: "Estado de los servidores"
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
